# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNBackgroundLocationSimpletest' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

# Third party deps
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'BatchedBridge',
#       'CxxBridge',
  ]
#  pod 'React', :path => '../node_modules/react-native'
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  # Pods for RNBackgroundLocationSimpletest

  target 'RNBackgroundLocationSimpletest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNBackgroundLocationSimpletestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNBackgroundLocationSimpletest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNBackgroundLocationSimpletest-tvOS
# commented out by Amy 2017-11-30
#  target 'RNBackgroundLocationSimpletest-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
